services:
  - type: web
    name: casas-precios-api
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.11
    buildCommand: |
      python -V
      python -m pip install --upgrade "pip>=25.2" "setuptools>=75.0.0" "wheel>=0.44.0"
      # Instalar dependencias desde wheels precompilados cuando existan
      python -m pip install --only-binary=:all: --prefer-binary -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
